version: "2"
services:
  scraper:
    image: teonite/test-scraper
    depends_on:
      - db
    entrypoint: scrapy crawl blog

  api:
    image: teonite/test-api
    ports:
      - "8080:8080"
    depends_on:
      - db
      - scraper
    entrypoint: python3 manage.py runserver 0.0.0.0:8080

  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scrape